name: Docker CI Pipeline

on:
  push:
    branches:
      - main  # Runs when code is pushed to main branch
  pull_request:
    branches:
      - main  # Runs on pull requests

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3️⃣ Build the Docker image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/llm-inference-image .

      # 4️⃣ Run container for testing
      - name: Run Container for Tests
        run: |
          docker run -d --name llm-inference-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/llm-inference-image
          sleep 5  # Wait for container to start

      # 5️⃣ Run basic test (Ensure container is running)
      - name: Test API
        run: curl -f http://127.0.0.1:5000 || exit 1

      # 6️⃣ Push image to Docker Hub (if tests pass)
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/llm-inference-image
